ENA/urls.py
from django.urls import path

from ENA import views

app_name = 'ENA'

urlpatterns = [
    path('character_list/', views.show_character_list, name='등장인물리스트'),
    path('<등장인물>/', views.show_character, name='등장인물'),
    # path('ena/', views.show_ena, name='ena'),
    # path('moony/', views.show_moony, name='moony'),
]

helloena/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # 이러이러한 url로 들어오면 이러이러한 함수를 실행해!
    # 주의, 함수 적을 때 괄호 적으면 안 됨.
    path('playground/', include('playground.urls')),
    path('ENA/', include('ENA.urls')),
    # path('playground/hello/', playground.views.say_hello, name='playground_hello'),
    # path('playground/hello_html/', playground.views.say_hello_html, name='playground_hello_html'),
    path('admin/', admin.site.urls),
]

playground/urls.py
from django.urls import path

from playground import views

app_name = 'playground'

urlpatterns = [
    path('hello/', views.say_hello, name='hello'),  # {% url 'playground:hello' %}
    path('hello_html/', views.say_hello_html, name='hello_html'),  # {% url 'playground:hello_html' %}
    path('bye_html/', views.say_bye_html, name='bye_html'),  # {% url 'playground:bye_html' %}
]

ENA/models.py
from django.db import models

# Create your models here.

ENA/views.py
from django.shortcuts import render

group = {
    'Characters': [
        {
            'title': 'ENA',
            'name': 'ena',
            'img_src':'ENA/images/May I help you sir.gif',
            # 'img_src': 'https://i.ytimg.com/vi/L2R9pmu0llk/maxresdefault.jpg',
        },
        {
            'title': 'ENA',
            'name': 'moony',
            'img_src':'ENA/images/moony.webp',
            # 'img_src': 'https://www.fangamer.com/cdn/shop/files/product_ena_moony_plush_main.png?crop=center&height=1200&v=1692229021&width=1800',
        },
        {
            'title': 'ENA',
            'name': 'merci',
            'img_src':'ENA/images/merci.png',
            # 'img_src': 'https://i.namu.wiki/i/TFEojh7xN347UTnIdHqCcVrjBkguvlvO0FeIU7lu3F1xchewM8DrZT584UDCKjp5maWs67ZYe0Awf9CQFe8_JA.webp',
        }
    ]
}


def show_ena(request):
    context = list(filter(lambda character: 'ena' in character['name'], group['Characters']))[0]
    # context = group['Characters'][0]
    return render(request, "ENA/등장인물.html", context=context)
    # return render(request, "ENA/ena.html")


def show_moony(request):
    context = list(filter(lambda character: 'moony' in character['name'], group['Characters']))[0]
    # context = group['Characters'][1]
    return render(request, "ENA/등장인물.html", context=context)
    # return render(request, "ENA/moony.html")


def show_character(request, 등장인물):
    context = list(filter(lambda character: 등장인물 in character['name'], group['Characters']))[0]
    return render(request, "ENA/등장인물.html", context=context)

def show_character_list(request):
    context = group         #{'char': [{등장인물1}, {등장인물2},]
    return render(request, 'ENA/character_list.html', context=context)

playground/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def say_hello(request):
    return HttpResponse("Hello World")

def say_hello_html(request):
    return render(request, "playground/hello.html", {'name':'지인아', 'greeting':'안뇽~'})

def say_bye_html(request):
    context = {
        'singer' : 'Adel',
        'title' : 'All I Ask'
    }
    return render(request, "playground/bye.html", context=context)

ENA/templates/ENA/character_list.html
{% extends 'base.html' %}

{% block title %} ENA - 등장인물들 {% endblock %}

{% block content %}
    <h1>{{ Characters.0.title }} - 등장인물</h1>
    <table class="table table-bordered align-middle">
        <tr>
            <th>이름</th>
            <th>프로필</th>
        </tr>

        {% for character in Characters %}
        <tr>
            {% load static %}
            <td><a href="{% url 'ENA:등장인물' 등장인물=character.name %}">{{ character.name }}</a></td>
            <td><img src="{% static character.img_src %}" style="height: 200px;"/></td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

ENA/templates/ENA/ena.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ENA - ena</title>
</head>
<body>
    <h1>ENA</h1>
<h2>ena</h2>
<img src="https://i.ytimg.com/vi/L2R9pmu0llk/maxresdefault.jpg" alt="Joel G - ENA"
     style="border-radius: 50%;"/>
</body>
</html>

ENA/templates/ENA/moony.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ENA - moony</title>
</head>
<body>
    <h1>ENA</h1>
<h2>moony</h2>
<img src="https://www.fangamer.com/cdn/shop/files/product_ena_moony_plush_main.png?crop=center&height=1200&v=1692229021&width=1800" alt="Joel G - Moony"
     style="border-radius: 50%;"/>
</body>
</html>

ENA/templates/ENA/등장인물.html
{% extends 'base.html' %}

{% block title %} {{ title }} - {{ name }} {% endblock %}

{% block content %}
    <h1 class="display-4">{{ title }}</h1>
    <a href=" {% url 'ENA:등장인물리스트' %} ">
        💬ENA 등장인물
    </a>
    <h2>{{ name }}</h2>
    {% load static %}
    <img src="{% static img_src %}" alt="{{ title }} - {{ name }}" style="border-radius: 50%;"/>
{% endblock %}

playground/templates/playground/bye.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bye</title>
</head>
<body>
    <h1>{{ singer }} - {{ title }}</h1>
    <br>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/wd9aAJjUlaQ?si=scJXuEcDR1X9QHeN" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    <hr>
    <h2>Lyrics</h2>
    <pre>
I will leave my heart at the door
I won't say a word
They've all been said before, you know
So why don't we just play pretend?
Like we're not scared of what's coming next
Or scared of having nothing left

Look, don't get me wrong
I know there is no tomorrow
All I ask is

If this is my last night with you
Hold me like I'm more than just a friend
Give me a memory I can use

Take me by the hand while we do what lovers do
It matters how this ends
'Cause what if I never love again?
I don't need your honesty
It's already in your eyes

And I'm sure my eyes, they speak for me
No one knows me like you do
And since you're the only one that matters
Tell me who do I run to?

Look, don't get me wrong
I know there is no tomorrow
All I ask is

If this is my last night with you
Hold me like I'm more than just a friend
Give me a memory I can use
Take me by the hand while we do what lovers do
It matters how this ends

'Cause what if I never love again?
Let this be our lesson in love
Let this be the way we remember us
I don't wanna be cruel or vicious
And I ain't asking for forgiveness
All I ask is

If this is my last night with you
Hold me like I'm more than just a friend
Give me a memory I can use
Take me by the hand while we do what lovers do
It matters how this ends
'Cause what if I never love again?
    </pre>
</body>
</html>

playground/templates/playground/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <B>Hello World!</B>
{# {% 파이썬 문법 %}#}
{# {{ 값 출력 }}#}
{{ name }}, {{ greeting }}
</body>
</html>